name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup/pnpm

      - name: Build packages
        run: pnpm run build

      - name: Create release pull request or publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm run version:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
